services:
  - type: web
    name: user-login-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DB_USER
        value: your_db_user
      - key: DB_PASS
        value: your_db_password
      - key: DB_NAME
        value: your_db_name
      - key: DB_HOST
        value: your_mysql_host (e.g., dbhost.render.com)
