runtime: python39
env: standard

env_variables:
  FLASK_SECRET_KEY: "your-secret-key"
  INSTANCE_CONNECTION_NAME: "your-project-id:region:instance-name"
  DB_USER: "your-db-user"
  DB_PASS: "your-db-password"
  DB_NAME: "your-database-name"

handlers:
- url: /.*
  script: auto